# Generated by Django 4.0.6 on 2023-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('broadcaststart', models.CharField(max_length=10)),
                ('broadcastfinish', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=900, verbose_name='genre')),
                ('registerdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
